name: Build and Deploy
on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'  # Set to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Or your build script

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: dist  # The folder the action should deploy.
        token: ${{ secrets.GITHUB_TOKEN }}  # Token for the action to authenticate.
        clean: false  # Automatically remove deleted files from the deploy branch
